[project]
name = "icd_tz"
authors = [
    { name = "elius mgani", email = "emgani@aakvatech.com"}
]
description = "Doctypes for Icd Tz"
requires-python = ">=3.14"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    "paramiko>=3.0.0",
]

[project.optional-dependencies]
dev = [
    "pre-commit",
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

# These dependencies are only installed when developer mode is enabled
[tool.bench.dev-dependencies]
# package_name = "~=1.1.0"

[tool.bench.frappe-dependencies]
frappe = ">=16.0.0,<17.0.0"
erpnext = ">=16.0.0,<17.0.0"

[tool.ruff]
line-length = 110
target-version = "py310"

[tool.ruff.lint]
select = ["F", "E", "W", "I", "UP", "B", "RUF"]
ignore = [
    "E402",
    "B017",
    "B018",
    "B023",
    "B904",
    "E101",
    "E501",
    "E741",
    "F401",
    "F403",
    "RUF001",
    "RUF002",
    "RUF003",
    "RUF012",
    "RUF013",
    "RUF015",
    "UP030",
    "UP031",
    "W191",
]
typing-modules = ["frappe.types.DF"]

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"
docstring-code-format = true
